RSPEC from sightings/users/sessions controller + Sighting model
CodeCoreYVR/find_my_pet pull request #13
Opened 2016-11-28 18:06 UTC by thaisamarinho

@blb451 @shofaizi , please take a look at this code.

Reuben and I did the RSPEC for sightings, users and sessions controller, besides the update on the sighting model after changing the columns in the table.
We had to delete the friendly ID for sightings because of errors when testing the update action as well.

Thanks a lot.
Thaisa and Reuben.

2016-11-28 19:04 UTC, blb451 commented
👍

2016-11-28 19:08 UTC, thaisamarinho commented
@whilestevego 
Steve, would you mind to review this code, please?

Thanks a lot.
Thaisa and Reuben

2016-11-29 17:36 UTC, whilestevego commented
@thaisamarinho can you resolve the conflicts? Your PR is next in line to review 👍

2016-11-29 17:56 UTC, thaisamarinho commented
@whilestevego conflicts were fixed.

2016-11-29 19:28 UTC, whilestevego requested changes
This looks good! I actually don't have a whole lot to suggest. There are a lot of code formatting issues, but I would prefer if rubocop addressed that than myself.

We need to add configure rubocop to also lint the tests, but don't worry about that for this PR. Fix the the few requests and it'll be ready to merge

2016-11-29 19:28 UTC, whilestevego commented on app/controllers/users_controller.rb
> +    end
Why not have a `before_action :authenticate_user` instead of this. The method is implemented in the `ApplicationController`?

2016-11-29 19:28 UTC, whilestevego commented on spec/controllers/sightings_controller_spec.rb
> +          sightings: attributes_for(:sighting) }
Can you put the open and closing braces on different lines, like so:

```ruby
 get :new, params: {
   sightings: attributes_for(:sighting)
}
```

2016-11-29 20:03 UTC, whilestevego approved these changes
![](http://i.imgur.com/UxuShGq.gif)

Looks good. Merge it. You may have to update your branch first.

2016-11-30 18:08 UTC, merged