Replace dummy data
CodeCoreYVR/find_my_pet pull request #15
Opened 2016-11-29 17:35 UTC by ninalouw

@thaisamarinho 
@mrreubenjones 
@jeffcstock 
@whilestevego 

I replaced the dummy data in the lost pets scroll screen next to the map. I created a file called home.js, I made ajax requests to get the JSON data, and I copied the relevant HTML from home/index.html.erb into my js functions. I also changed the image_uploader to use fog only if in production.

2016-11-29 17:43 UTC, whilestevego commented
@ninalouw good description. I clearly know what you did. However, when tagging someone for review. Only tag one person at a time.

2016-11-29 18:01 UTC, thaisamarinho commented on app/assets/javascripts/home.js
> +       console.log(pets[0])
Do you still need to console.log[0] over there?

2016-11-29 18:10 UTC, thaisamarinho reviewed
Nina, Great job! Awesome work over here. I made some small comments. Thanks!!

2016-11-29 18:10 UTC, thaisamarinho commented on app/assets/javascripts/home.js
> +      <img class='img-circle' src="${pet.image}" alt="" />
have you check this code to see if works with a pet with more than one picture on its profile? the fact that there is pet.image makes me think about what if this pet has 2 or 3 images...

2016-11-29 18:10 UTC, thaisamarinho commented on app/views/home/index.html.erb
>            <% if user_signed_in? %>
can you indent this code? Maybe is already indented, but this file is so big that i think i got lost.

2016-11-29 18:28 UTC, ninalouw commented on app/assets/javascripts/home.js
> +       console.log(pets[0])
Deleted :)

2016-11-29 18:28 UTC, ninalouw commented on app/assets/javascripts/home.js
> +      <img class='img-circle' src="${pet.image}" alt="" />
I'll look into that now, good point!

2016-11-29 18:33 UTC, ninalouw commented on app/assets/javascripts/home.js
> +      <img class='img-circle' src="${pet.image}" alt="" />
It works! In the report it shows 3 images, and in the Lost pet scrollbar it just shows the first one :)

2016-11-29 18:34 UTC, ninalouw commented on app/views/home/index.html.erb
>            <% if user_signed_in? %>
Yes I dont really understand the indentation here either, I'll make some changes and then I'll push it all up again :)

2016-11-29 19:28 UTC, ninalouw commented
@whilestevego , @thaisamarinho  has already reviewed this and it seems to be working :)

2016-11-30 20:12 UTC, whilestevego requested changes
You have a `.DS_Store` file in here. It should not be there. Can you add ignore rules for MacOS? Go to https://www.gitignore.io/ and remove this

2016-12-01 18:32 UTC, whilestevego requested changes
Few changes to do

2016-12-01 18:32 UTC, whilestevego commented on app/uploaders/image_uploader.rb
> +  # Create different versions of your uploaded files:
Can you delete these comments?

2016-12-01 18:32 UTC, whilestevego commented on app/uploaders/image_uploader.rb
> +  # end
Delete these too.

2016-12-01 18:32 UTC, whilestevego commented on app/assets/javascripts/home.js
> + });
Indenting levels are off here. 📇

2016-12-01 18:32 UTC, whilestevego commented on app/assets/javascripts/home.js
> +$(document).ready(function(){
Can you add a space after `()`?

2016-12-01 18:32 UTC, whilestevego commented on app/uploaders/image_uploader.rb
> +
Delete these comments to?

2016-12-02 19:31 UTC, whilestevego approved these changes
Merging this

2016-12-02 19:31 UTC, merged