"add README"
CodeCoreYVR/find_my_pet pull request #2
Opened 2016-11-23 19:40 UTC by octothorpus

Please add your own name &/ github name.

2016-11-23 19:42 UTC, ninalouw commented on README.md
> +Find my Pet is a web application which is intended to be used as a place for pet owners
Find my Pet is a web application which enables pet owners...

2016-11-23 19:42 UTC, ninalouw commented on README.md
> +to report missing pets, for the public to report missing pet sightings, with the intention
and the public to report...

2016-11-23 19:44 UTC, ninalouw commented on README.md
> +- rails db:create db:migrate db:seed
Use backticks `` to tell markdown to format this as code.

2016-11-23 19:44 UTC, ninalouw commented on README.md
> +Project Description
Use Markdown ## to format this as an H2

2016-11-23 19:44 UTC, ninalouw commented on README.md
> +Setup Instructions:
Use ## to format this as an H2

2016-11-23 19:45 UTC, ninalouw commented on README.md
> +Keys required:
add ## to format this as h2

2016-11-23 19:45 UTC, ninalouw commented on README.md
> +ENV["email_user_name"] = "..."
Use `` to format this as code

2016-11-23 19:45 UTC, ninalouw commented on README.md
> +List Of Contributors:
add ## to format this as an H2

2016-11-23 19:47 UTC, ninalouw requested changes
Please look into markdown syntax and use this to format this README correctly. Perhaps look at another README as an example of how to lay this all out.

2016-11-25 17:35 UTC, ninalouw reviewed
Could you add a link to the heroku version and say:
View the live version of the application here: `link`

2016-11-28 18:11 UTC, octothorpus commented
@ninalouw I made the changes you requested. Thank you!

2016-11-29 17:32 UTC, whilestevego commented
@ninalouw can you check if this is ready for approval?

2016-11-29 17:57 UTC, ninalouw reviewed
Looks good :)

2016-11-29 17:57 UTC, ninalouw approved these changes

2016-11-29 18:11 UTC, merged