Test pet model
CodeCoreYVR/find_my_pet pull request #5
Opened 2016-11-24 17:46 UTC by shofaizi

2016-11-24 17:51 UTC, jeffsmw2 approved these changes
👍

2016-11-24 18:34 UTC, whilestevego requested changes

2016-11-24 18:34 UTC, whilestevego commented on Gemfile
> +  gem "rspec-rails", :group => [:development, :test]
This `gem` is already in the `:development` and `:test` group. There is no need to specify it twice. Also, other gems use `'`. Don't use `"`

2016-11-24 18:34 UTC, whilestevego commented on spec/models/message_spec.rb
> +
Remove this empty line

2016-11-24 18:34 UTC, whilestevego commented on spec/rails_helper.rb
> +  # config.filter_gems_from_backtrace("gem name")
Get rid of all the comments in this file! 🔥🔥🔥🔥🔥

2016-11-24 18:34 UTC, whilestevego commented on spec/spec_helper.rb
> +=end
🔥🔥🔥🔥 the comments!

2016-11-24 18:44 UTC, shofaizi commented
@whilestevego  took care of the changes pls approve

2016-11-25 17:17 UTC, whilestevego commented
@shofaizi why did you close the PR?

2016-11-25 17:43 UTC, shofaizi commented
@whilestevego

2016-11-25 17:56 UTC, whilestevego commented
@shofaizi solve the conflicts. Come see if you're unsure how 😎

2016-11-25 18:41 UTC, whilestevego commented
This branch is irrelevant. Pet tests were added as part of https://github.com/CodeCoreYVR/find_my_pet/pull/7

2016-11-25 18:41 UTC, closed without merging