add friendly id and some bug fixes
CodeCoreYVR/find_my_pet pull request #8
Opened 2016-11-24 18:48 UTC by ninalouw

@thaisamarinho 
@mrreubenjones 
Will you guys please take a look?

2016-11-24 19:58 UTC, mrreubenjones commented on app/models/sighting.rb
> +      :pet_type,
Would consider removing this line, as the pet_type would be populated pretty quick.

2016-11-24 19:58 UTC, reuben-jones approved these changes
Looks awesome. 

See note in the sighting.rb file, but it's just a minor thing.

2016-11-24 20:00 UTC, mrreubenjones commented
@jeffcstock @ninalouw 

We think it's just wonderful. Feel free to send on to Steve. :)

2016-11-24 20:12 UTC, jeffcstock commented
Thanks for reviewing @mrreubenjones @thaisamarinho, now it's your turn @whilestevego!

2016-11-25 17:39 UTC, whilestevego requested changes
Looking good. There are only a few changes to do

![](http://i.imgur.com/l7tSz92.jpg)

2016-11-25 17:39 UTC, whilestevego commented on app/models/sighting.rb
> +  extend FriendlyId
Can you move this line to the top of the class?

2016-11-25 17:39 UTC, whilestevego commented on app/models/sighting.rb
> +  friendly_id :slug_candidates, use: [:slugged, :history]
Add an empty line after this one to separate it from the method below

2016-11-25 17:39 UTC, whilestevego commented on config/initializers/friendly_id.rb
> +  # }
Can you delete on the info comments in here?

2016-11-25 17:49 UTC, jeffcstock commented
Please review our edits again @whilestevego.

2016-11-25 18:20 UTC, whilestevego approved these changes
![](http://i.imgur.com/w5sTjl1.gif)

2016-11-25 18:53 UTC, merged